CALENDAR_PROTOTYPES = [
    # Semester starts
    "when does fall semester start",
    "when does spring semester start",
    "when does summer semester start",
    "when does summer session 1 start",
    "when does summer session 2 start",
    "when do coursera a session courses begin",
    "when do coursera b session courses begin",
    "when does the ID full semester start",
    "when do institute of design courses begin",
    # Breaks and holidays
    "when is spring break",
    "when is fall break",
    "when is thanksgiving break",
    "winter break dates",
    "labor day no classes",
    "when is juneteenth day",
    "when is independence day observed",
    "when is christmas day",
    "when is new years day",
    "when is the floating holiday",
    # Month + holiday/break queries
    "january holiday",
    "february holiday",
    "march holiday",
    "march break",
    "april holiday",
    "may holiday",
    "june holiday",
    "july holiday",
    "august holiday",
    "september holiday",
    "october holiday",
    "october break",
    "november holiday",
    "november break",
    "december holiday",
    "december break",
    "holiday in january",
    "holiday in february",
    "holiday in march",
    "holiday in april",
    "holiday in may",
    "holiday in june",
    "holiday in july",
    "holiday in august",
    "holiday in september",
    "holiday in october",
    "holiday in november",
    "holiday in december",
    "any holidays in january",
    "any holidays in february",
    "any holidays in march",
    "any holidays in april",
    "any holidays in may",
    "any holidays in june",
    "any holidays in july",
    "any holidays in august",
    "any holidays in september",
    "any holidays in october",
    "any holidays in november",
    "any holidays in december",
    "is there a holiday in january",
    "is there a holiday in february",
    "is there a holiday in march",
    "is there a holiday in april",
    "is there a holiday in may",
    "is there a holiday in june",
    "is there a holiday in july",
    "is there a holiday in august",
    "is there a holiday in september",
    "is there a holiday in october",
    "is there a holiday in november",
    "is there a holiday in december",
    "what holidays are in january",
    "what holidays are in february",
    "what holidays are in march",
    "what holidays are in april",
    "what holidays are in may",
    "what holidays are in june",
    "what holidays are in july",
    "what holidays are in august",
    "what holidays are in september",
    "what holidays are in october",
    "what holidays are in november",
    "what holidays are in december",
    "university closed in january",
    "university closed in february",
    "university closed in march",
    "university closed in april",
    "university closed in may",
    "university closed in june",
    "university closed in july",
    "university closed in august",
    "university closed in september",
    "university closed in october",
    "university closed in november",
    "university closed in december",
    # Registration and add/drop
    "when does fall registration begin",
    "when does spring registration begin",
    "registration start date",
    "add drop deadline",
    "last day to drop a class",
    "when does the add drop period end",
    "early departure dates",
    # Grade and exam deadlines
    "when are final grades due",
    "when are fall incomplete grades due",
    "when is the final exam week",
    "final exam schedule release date",
    "when do final exams start",
    "grades due at noon",
    "when are online session A grades due",
    "summer 1 final grades deadline",
    "summer 2 final grades deadline",
    "coursera summer term grades due",
    # Schedule publication
    "when is the fall course schedule published",
    "when is the spring course schedule published",
    "fall final exam schedule published online",
    "course schedule publication date",
    # Degree conferral and graduation
    "when is fall degree conferral",
    "when is spring commencement",
    "when are graduation applications due",
    "fall degree conferral applications due",
    # Last day of courses
    "last day of classes summer 1",
    "last day of classes summer 2",
    "last day of courses coursera a",
    "last day of courses coursera b",
    "when does the fall term start"
]