CALENDAR_PROTOTYPES = [
    # Semester starts
    "when does fall semester start",
    "when does spring semester start",
    "when does summer semester start",
    "when does summer session 1 start",
    "when does summer session 2 start",
    "when do coursera a session courses begin",
    "when do coursera b session courses begin",
    "when does the ID full semester start",
    "when do institute of design courses begin",
    # Breaks and holidays
    "when is spring break",
    "when is fall break",
    "when is thanksgiving break",
    "winter break dates",
    "labor day no classes",
    "when is juneteenth day",
    "when is independence day observed",
    "when is christmas day",
    "when is new years day",
    "when is the floating holiday",
    # Registration and add/drop
    "when does fall registration begin",
    "when does spring registration begin",
    "registration start date",
    "add drop deadline",
    "last day to drop a class",
    "when does the add drop period end",
    "early departure dates",
    # Grade and exam deadlines
    "when are final grades due",
    "when are fall incomplete grades due",
    "when is the final exam week",
    "final exam schedule release date",
    "when do final exams start",
    "grades due at noon",
    "when are online session A grades due",
    "summer 1 final grades deadline",
    "summer 2 final grades deadline",
    "coursera summer term grades due",
    # Schedule publication
    "when is the fall course schedule published",
    "when is the spring course schedule published",
    "fall final exam schedule published online",
    "course schedule publication date",
    # Degree conferral and graduation
    "when is fall degree conferral",
    "when is spring commencement",
    "when are graduation applications due",
    "fall degree conferral applications due",
    # Last day of courses
    "last day of classes summer 1",
    "last day of classes summer 2",
    "last day of courses coursera a",
    "last day of courses coursera b",
    "when does the fall term start"
]