CONTACTS_PROTOTYPES = [
    # Generic contact lookup phrasing
    "how do i contact a department",
    "who do i email at the university",
    "what is the phone number for",
    "where is the office located",
    "campus directory contact",
    # Registrar
    "how do i contact the registrar",
    "registrar office contact",
    "where is the registrar office",
    "who do i email about transcripts",
    # Admissions
    "admissions office contact",
    "graduate admissions contact",
    "who handles admissions",
    # Financial
    "financial aid office phone number",
    "who manages student accounts",
    "who do i talk to about tuition",
    # Specific colleges and departments
    "armour college of engineering contact",
    "college of computing contact info",
    "chicago-kent college of law contact",
    "college of architecture contact",
    "stuart school of business contact",
    "department of computer science contact",
    "department of physics phone number",
    "department of chemistry email",
    "department of biology contact",
    "department of applied mathematics contact",
    "department of psychology contact",
    "biomedical engineering department contact",
    "chemical and biological engineering department",
    "electrical and computer engineering contact",
    "department of IT and management",
    "civil architectural environmental engineering",
    "ed kaplan institute contact",
    "english language services contact",
    "food science and nutrition contact",
    "empowerment leadership mentorship program",
    # Role-based lookups
    "who is the department chair",
    "who is the dean of undergraduate affairs",
    "who is the provost",
    "who is the president of illinois tech",
    "who is the president of iit",
    "illinois tech president",
    "iit president",
    "who leads illinois tech",
    "university president contact",
    "who runs academic advising",
    "who handles transfer credit",
    "who handles probation appeals",
    "who enforces academic policy",
    "student services contact",
    "what is the IT help desk phone number",
    "who do i talk to about graduate programs",
    "institute contact information",
    "academic department phone number",
    "college administrative office contact",
    "department of food science contact",
    "who do i contact in the college of architecture"
]