DOCUMENTS_PROTOTYPES = [
    # Transcripts — official records, ordering, Parchment (router must rank DOCUMENTS)
    "how do i get an official transcript from iit",
    "how do i order an official transcript",
    "can i order an official transcript online",
    "is there a fee for ordering an official transcript",
    "how to request my transcript illinois tech",
    "order transcript online",
    "get a copy of my academic transcript",
    "official transcript pdf electronic",
    "parchment transcript ordering",
    "where do i order transcripts iit",
    "student transcript request process",
    "how long does a transcript take",
    "transcript hold financial balance",
    "printed copy of transcript unofficial",
    "law school transcript conviser registrar",
    "alumni transcript request",
    "third party transcript national student clearinghouse",
    # Student handbook / co-terminal
    "what does the student handbook say",
    "co-terminal student handbook policies",
    "what are the co-terminal program rules",
    "what is the coterminal program",
    # Graduate academic policies
    "graduate academic policies",
    "what is the gpa requirement for graduation",
    "academic probation policy",
    "minimum gpa requirement",
    "academic standing rules",
    "how probation works university",
    "policy for academic dismissal",
    "grading policy university",
    "grade legend explanation",
    "what grades count toward gpa",
    "honors graduation requirements",
    "credit hour requirements",
    # Registration policies
    "registration rules",
    "policy for dropping a course",
    "withdrawal policy university",
    "leave of absence policy",
    "course repeat policy",
    "transfer credit rules",
    "incomplete grade policy",
    "auditing a course rules",
    # Registrar policies
    "what is the hardship withdrawal process",
    "policies hardship",
    "registrar academic policies",
    "registration hold on my account",
    "how do i clear a hold",
    # Financial aid policies
    "financial aid academic requirements",
    "financial responsibility policy",
    "satisfactory academic progress policy",
    # Conduct and integrity
    "student conduct rules",
    "academic integrity policy",
    "what happens if i cheat",
    "plagiarism consequences",
    "code of conduct university",
    "alcohol and drug policy",
    "what is the amnesty policy",
    "FERPA student records policy",
    "what is FERPA",
    "what is ferpa",
    "FERPA rights",
    "ferpa rights",
    "who can access my records",
    "can my parents see my grades",
    "student privacy rights",
    # Scholarships
    "what is a scholarship",
    "scholarship opportunities",
    "scholarship overview",
    "types of scholarships",
    "scholarship eligibility",
    "scholarship gpa requirement",
    "do i qualify for a scholarship",
    "merit scholarship",
    "institutional scholarship",
    "scholarship renewal",
    "title ix policy",
    "sexual misconduct policy",
    "disciplinary sanctions",
    "disruptive conduct policy",
    # Commencement and graduation
    "commencement policies",
    "graduation requirements university",
    "degree conferral requirements",
    # Coursera / events
    "coursera program policies",
    "events and schedules policy",
    "student directory policies",
    # ID and campus access
    "hawkcard policy",
    "student id card rules",
    "campus id card illinois tech",
    "can i lend my hawkcard",
    "lost hawkcard replacement",
    # Campus alerts and safety
    "iitalert notification system",
    "campus emergency alert",
    "how does iitalert work",
    "campus safety notifications",
    # Academic support services
    "academic resource center tutoring",
    "arc tutoring services",
    "peer tutoring illinois tech",
    "tutoring for calculus",
    "academic support services",
    # Career services
    "career services illinois tech",
    "handshake internship platform",
    "job search career services",
    "resume writing workshop",
    "interview preparation career services",
    # Library and technology
    "galvin library services",
    "library printing credits",
    "free printing students",
    "3d printing campus",
    "idea shop maker space",
    "grainger maker space equipment",
    "laser cutter campus",
    # Student support services
    "confidential advisor services",
    "sexual misconduct reporting",
    "resilience confidential advisor",
    "community affairs office",
    "volunteer opportunities campus",
    # Fraternities and sororities
    "fraternities sororities illinois tech",
    "greek life illinois tech",
    "how many fraternities illinois tech",
    "fraternity chapter house",
    "greek council recognition",
    # Fees and financial
    "graduation fee policy",
    "student activity fee allocation",
    "umii scholarship fee",
    "printing credits per semester",
    "graduate continuation fee",
    # Grade types
    "na grade non attendance",
    "incomplete grade undergraduate",
    "incomplete grade graduate",
    "grade appeal process",
    "change of grade policy",
    # Transfer and credit
    "transfer credit policy",
    "external transfer credit",
    "doctoral transfer credit",
    "masters transfer credit",
    "unaccredited institution transfer",
    # Co-terminal specific
    "co-terminal financial aid",
    "co-terminal scholarship extension",
    "co-terminal federal aid",
    "co-terminal gpa requirement",
    "co-terminal advising",
    # Health insurance
    "student health insurance requirement",
    "ship health insurance",
    "international student insurance",
    "health insurance waiver",
    # Registration specifics
    "registration pin illinois tech",
    "enrollment verification",
    "national student clearinghouse",
    "degree verification",
    # Housing and residence
    "residence requirements undergraduate",
    "on campus housing policy",
    "housing guarantee",
    # Conduct appeals
    "appeal academic honesty decision",
    "code of conduct appeal",
    "expulsion review process",
    "suspension appeal",
    # Intellectual property
    "intellectual property policy",
    "student research ownership",
    "third party sponsorship work",
    # Parking
    "how does parking work on campus",
    "student parking permit policy",
    "visitor parking rules",
    "daily parking rates campus",
    "where can I park at IIT",
    "parking regulations illinois tech",
    # Course load and enrollment
    "maximum course load per semester",
    "how many courses can I take per semester",
    "maximum credit hours per semester",
    "full time credit hour requirement",
    "course overload policy",
    "minimum credit hours for full time status",
    "part time enrollment credit hours",
    # Attendance
    "class attendance policy",
    "attendance requirements",
    "what is the attendance policy at IIT",
    "can professors take attendance",
    "attendance and registration policy",
    # Leave of absence — casual phrasing
    "i need a break from school",
    "i want to take time off from classes",
    "i need to step away from school",
    "i want to pause my studies",
    "can i stop going to school for a semester",
    "i need to stop attending classes",
    # Late registration
    "late registration policy",
    "how do I request a late registration",
    "late add request process",
    "can I register after the deadline",
    # CTA U-Pass / transit
    "how do I get a Chicago transit card",
    "how do I get a CTA U-Pass",
    "student transit pass Illinois Tech",
    "CTA U-Pass for IIT students",
    "how to get a Ventra card as a student",
    "public transit card for students",
    # Faculty grade submission
    "how do I submit final grades",
    "how to enter grades as a professor",
    "faculty grade submission process",
    "where do I submit student grades",
    "grade submission portal for faculty",
    "how to submit grades illinois tech",
    # Financial distress / hardship
    "i cant pay my tuition right now",
    "i cannot afford tuition this semester",
    "i dont have money to pay for school",
    "will they kick me out if i dont pay tuition",
    "what happens if i cant pay my bill",
    "is there any way to get help paying for school",
    "financial hardship tuition help",
    "i need help paying for school",
    "how do i know how much i owe the school",
    "where can i see my account balance",
    "tuition payment plan options",
    "can i get a payment plan for tuition",
]