OOD_PROTOTYPES = [
    # Sports and ticketing
    "where can I buy tickets to an NBA game",
    "how do I get tickets to an NFL football game",
    "where to buy concert tickets online",
    "how much do sports event tickets cost",
    "where to purchase tickets for entertainment events",
    # Sports scores and results
    "who won the NBA finals",
    "what team won the Super Bowl this year",
    "who is the current NBA champion",
    "what are today's NBA scores",
    "who won the World Series",
    "what was the score of last night's game",
    "who won the championship game",
    "what NFL team is in first place",
    "who won the NCAA tournament",
    "what are the playoff standings",
    # Commerce and shopping
    "where can I buy something online",
    "how do I shop for products on the internet",
    "what is the best online store for electronics",
    "how to return a product I bought online",
    "where can I find deals on consumer goods",
    # Entertainment and media
    "what streaming service should I subscribe to",
    "how do I watch live sports on TV",
    "what are the best video games right now",
    "how do I listen to music online",
    "where can I watch movies and TV shows",
    # Weather and environment
    "what is the weather forecast for Chicago",
    "what is the weather in Chicago today",
    "what is the weather like in Chicago",
    "how cold is it in Chicago right now",
    "current weather in Chicago",
    "Chicago weather today",
    "is it going to rain tomorrow",
    "what is the temperature outside right now",
    "will it snow this weekend in Chicago",
    # Food and restaurants
    "what is the best coffee shop near IIT",
    "where can I get pizza near campus",
    "recommend a good restaurant in Bronzeville",
    "best Thai food near Illinois Tech",
    "where should I eat lunch today",
    # Jobs and companies outside IIT
    "how do I get a job at Google",
    "what are the admission requirements for Harvard Law School",
    "how to apply to MIT graduate program",
    "what is the salary for a software engineer at Apple",
    "how much does a data scientist make",
    # Personal advice and philosophy
    "can you write my essay for me",
    "write my homework assignment",
    "do my project for me",
    "help me solve this math problem",
    "what should I wear to a party",
    "how do I make friends in college",
    "what is the meaning of life",
    "what is the purpose of existence",
    "tell me a joke",
    "what do you think about politics",
    # Entertainment and media
    "what movies are playing this weekend",
    "who won the game last night",
    "what is the best show on Netflix",
    "when does the new Marvel movie come out",
    "what song is number one right now",
    # General knowledge / trivia
    "what is the capital of France",
    "what is the capital of Germany",
    "what is the capital of Japan",
    "what is the largest country in the world",
    "who is the president of the United States",
    "who is the president of Russia",
    "who is the prime minister of Canada",
    "who is the prime minister of the United Kingdom",
    "who is the king of England",
    "who invented the telephone",
    "who discovered gravity",
    "who discovered electricity",
    "who is the richest person in the world",
    "who is the CEO of Tesla",
    "how far is the moon from earth",
    "how far is the sun from earth",
    "what year did World War II end",
    "when was the Declaration of Independence signed",
    "explain quantum physics to me",
    "what is the speed of light",
    "how many planets are in the solar system",
    "what is the population of China",
    "who wrote Romeo and Juliet",
    "what is the tallest mountain in the world",
    # Technology and personal devices
    "how do I fix my laptop",
    "what phone should I buy",
    "how to reset my WiFi password at home",
    "best laptop for college students",
    "how do I download an app",
    # Shopping and personal finance
    "where can I buy cheap textbooks",
    "how to open a bank account",
    "what credit card is best for students",
    "how to save money as a student",
    "where is the nearest grocery store",
    # Travel and transportation
    "how do I get to O'Hare airport from campus",
    "cheapest flights to New York",
    "how long is the drive to Milwaukee",
    "best vacation spots for spring break",
    "how do I rent a car in Chicago",
    # Health and personal
    "how to lose weight fast",
    "what should I do if I have a cold",
    "best workout routine for beginners",
    "how many hours of sleep do I need",
    "what is a healthy diet for students",
]
