TUITION_PROTOTYPES = [
    # General tuition cost questions
    "what is the tuition for the current academic year",
    "how much does it cost to attend",
    "how much is tuition per semester",
    "how much is tuition per credit hour",
    "what are the tuition rates",
    "what is the graduate tuition amount",
    "what is the undergraduate tuition amount",
    "how much is part time tuition",
    # School-specific tuition
    "Chicago-Kent tuition",
    "chicago kent college of law tuition",
    "Institute of Design tuition",
    "institute of design ID tuition fees",
    "Stuart School of Business tuition",
    "stuart business school cost per credit",
    "Mies campus tuition",
    "mies campus graduate tuition",
    "LLM tuition and fees",
    "what is the LLM program cost",
    "coursera program tuition rate",
    "online program tuition",
    # Mandatory fees
    "what are the mandatory fees",
    "student activity fee",
    "what is the activity fee per semester",
    "student service fee",
    "what is the student services fee",
    "health insurance fee",
    "student health insurance cost",
    "CTA U-Pass fee",
    "how much is the upass",
    "opt out upass fee",
    "opt in upass part time",
    # Specific fees
    "chicago kent fitness center fee",
    "course fee legal english",
    "mediation clinic course fee",
    "employment litigation course fee",
    "application fee amount",
    "graduation application fee",
    # Program and enrollment type fees
    "full time enrollment tuition",
    "part time enrollment tuition",
    "what is the cost for a certificate program",
    "intensive english program tuition",
    "how much does summer session cost",
    "summer tuition rate",
    # Comparison and billing period
    "tuition billing period",
    "how is tuition billed",
    "tuition per academic year",
    "cost comparison by school",
    "how do fees compare between programs",
    "what fees are charged each semester",
    "how much is the graduate program fee",
    # Casual / natural language cost questions
    "whats the cost",
    "how much does it cost",
    "how much do i have to pay",
    "how much will i pay",
    "what do i owe",
    "what am i paying",
    "i wanna know about tuition",
    "tell me about tuition",
    "money for school",
    "how expensive is iit",
]